### ISSUE TITLE
Cant load dataset

### ISSUE THREAD

**Issue by Rajashreegr** [elastic/stack-docker#61] opened 2018-10-21 05:01 UTC
I set up the elastic search and all the containers are up & running.  

But I'm facing an issue while loading the dataset to elastic search. I setup the mappings & trying to load dataset [
I'm following the Tutorial - https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html.]

On running the curl upload command -
curl -H 'Content-Type: application/x-ndjson' -XPOST 'localhost:9200/bank/account/_bulk?pretty' --data-binary @accounts.json,
I'm getting the error 'curl: (52) Empty reply from server'.

On listing the docker containers it shows the below containers are running successfully.
docker.elastic.co/kibana/kibana:6.3.0 "/usr/local/bin/kiba…" 2 hours ago Up 2 hours (healthy) 0.0.0.0:5601->5601/tcp kibana
a3aa8556c225 docker.elastic.co/logstash/logstash:6.3.0 "/usr/local/bin/dock…" 2 hours ago Up 2 hours (healthy) 5044/tcp, 9600/tcp logstash
79c75ecde762 docker.elastic.co/elasticsearch/elasticsearch:6.3.0 "/usr/local/bin/dock…" 2 hours ago Up 2 hours (healthy) 0.0.0.0:9200->9200/tcp, 9300/tcp elasticsearch

But when I checked for [http://localhost:9200/bank ] it is not up & running. Not sure what is wrong here.

**Comment by fxdgear** [comment] 2018-10-22 14:42
@Rajashreegr soo it looks to me like `stack-docker` is functioning properly and as intended. 

The bigger issue is getting your dataset into Elasticesarch. 

So can you check a few things for me... 

1: navigate to `localhost:9200` in your browser and login with the username/password `elastic`/<password provided by the setup>`
2. navigate to `localhost:5600` and use the same username and password. 

This is going to check that es and kibana are running and accessible via your host machine. 

If both of those work, I'd suggest trying a few commands in the kibana console to try creating the index you wanna bulk index into delete the index. 

if that works we well then we need to try doing a "bulk" load via kibana console (small subset of your data maybe 2-3 lines of your `accounts.json` file. 

If that works then I'm going to say we need to look at the `accounts.json` and see if it's maybe too big for the size of the cluster..

**Comment by ErikWallin** [comment] 2018-10-22 16:15
Have you managed to turn off ssl? I have to use https.

**Comment by Rajashreegr** [comment] 2018-10-28 04:16
I disabled the xpack ssl security in elasticsearch.yml file.
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

Now the elastic search started properly but facing some other issue.  When I run the curl command on the Elastic search URL - http://localhost:9200, I'm getting the following output.
{
  "name" : "xitm0Cn",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "9N0lMgLVSWmipPgThJ_JoA",
  "version" : {
    "number" : "6.3.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "424e937",
    "build_date" : "2018-06-11T23:38:03.357887Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

Now the Kibana & logstash are not able to reach elastic search and keep waiting for its connection.

**Comment by fxdgear** [comment] 2018-10-28 23:57
@Rajashreegr 

So lets go back and start at the beginning. 

all you have to do to get the data set to load is run 

```
curl -H 'Content-Type: application/x-ndjson' -u 'elastic:<your_elastic_password>' -k -XPOST 'https://localhost:9200/bank/account/_bulk?pretty' --data-binary @accounts.jso
```

**Comment by fxdgear** [comment] 2018-11-29 23:05
Closing. @Rajashreegr if you're continue to having issues after using `https` in your curl to load the data please re-open the issue. Thanks

**Closed by fxdgear** 2018-11-29 23:05 UTC
